-- =====================================================================
-- V5 — Audit log (Phase 18)
-- One immutable row per important state-changing HR action. Actor data is
-- denormalized on purpose: the audit trail must stay readable even when a
-- user is later renamed, disabled, or removed, so it is never joined back
-- to USERS for display.
-- =====================================================================

CREATE TABLE AUDIT_LOG (
    ID           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ACTOR_ID     NUMBER(19),
    ACTOR_EMAIL  VARCHAR2(150),
    ACTOR_NAME   VARCHAR2(150),
    ACTOR_ROLE   VARCHAR2(20),
    ACTION       VARCHAR2(60)  NOT NULL,
    ENTITY_TYPE  VARCHAR2(40)  NOT NULL,
    ENTITY_ID    NUMBER(19),
    ENTITY_LABEL VARCHAR2(200),
    DETAILS      VARCHAR2(1000),
    CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IX_AUDIT_CREATED ON AUDIT_LOG (CREATED_AT);
CREATE INDEX IX_AUDIT_ACTION  ON AUDIT_LOG (ACTION);
CREATE INDEX IX_AUDIT_ENTITY  ON AUDIT_LOG (ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IX_AUDIT_ACTOR   ON AUDIT_LOG (ACTOR_ID);
